### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by Mozarslan** [neu-ma-tic/test9475#1]
Bro you have copied my code and even with my token. Can you please delete it or update as yours (commands etc.) and change the token

**Comment by lginlangl** [comment]
https://user-images.githubusercontent.com/17932849/211062142-8a2dcd07-df50-4bbf-a827-9b9cf8f77e0b.mp4

**Comment by Mozarslan** [comment]
Yeah there is nothing bad at using my code but chancing the token and name of the bot is enough for me

**Comment by neu-ma-tic** [comment]
@lginlangl thank you for this masterpiece.

**Comment by neu-ma-tic** [comment]
why did it send twice lol
